name: Github Action CI/CD # 스크립트 돌렸을 때 나오는 이름 설정

on: # 어떤 브랜치에 push 됐을 때 적용할 것인지 설정
  push:
    branches:
      - main  # main 브랜치에 push 될 때 CI/CD가 동작한다.

env:  # 환경 변수 설정 : 변할 수 있는 변수들을 여기서 설정해두고 key를 가져가 쓰기위함
  S3_BUCKET_NAME: henjune-s3
  CODE_DEPLOY_APPLICATION_NAME: MY-CODE-DEPLOY
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CODE-DEPLOY-GROUP

jobs: # jobs에 이제 실행할 동작들을 정의해준다.
  build:
    runs-on: ubuntu-latest  # 해당 jobs가 어떤 환경에서 돌아갈 것인지 설정

    steps:
      - name: Checkout  # 이름을 지정하면 어떤 작업인지 보기 편하니까 name을 원하는대로 설정
        uses: actions/checkout@v2 # uses에는 어떤 행위를 해야하는지 설정

      - name: Set up JDK 11
        uses: actions/setup-java@v1 # 자바를 사용하기 때문에 jdk 버전 지정
        with:
          java-version: 11  # 자바 버전 11로 

      - name: Gradle execute permission for gradlew # Gradle로 빌드할 것이며, 빌드를 하기위한 gradlew에 권한을 부여
        run: chmod +x ./gradlew
        shell: bash # 돌아가는 환경을 bash shell로 하겠다.

      - name: Build with Gradle 
        run: ./gradlew build  # 실제 빌드 하기
        shell: bash

      - name: Make zip file 
        run: zip -r ./$GITHUB_SHA . # 결과된 파일을 하나의 zip 파일로 압축해서 올리자. GITHUB_SHA : 중복되지 않는 값을 출력해준다.
        shell: bash
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1  # aws에 접속하고 aws를 사용하기위한 권한 등록
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Github Action에 secret key 설정해 놓은 것들
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip # 압축된 결과 파일을 s3 저장소에 올리기

      # CodeDeploy를 사용해서 s3에 올라가있는 압축 파일을 가져다가 배포 하기
      - name: Code Deploy 
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
